### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by ciw-ws** [lzha106/FDDB-tools-for-windows#1]
Dear @lzha106 , 
Thanks for this great work. 
It works perfect on windows without complex modification.
There's a little requirement in my usage which needs a slightly modification in the source code, is it possible for you to provide me those code? 
Anyway, thanks a lot for your great work.

**Comment by lzha106** [comment]
Thanks for the try. 
You can find official source code from http://vis-www.cs.umass.edu/fddb/evaluation.tgz and make changes as you wish.
